Fix fonts on NixOS and any other XDG-compliant distro with unusual directory structure
LadybirdWebBrowser/ladybird pull request #31
Opened 2024-06-03 20:44 UTC by easrng

NixOS doesn't have `/usr/share/fonts`, so Ladybird was only loading the default bitmap font. This fixes that by replacing hardcoded paths (`/usr/share/fonts`, `/usr/local/share/fonts`, `$HOME/.local/share/fonts`) with their XDG base directory equivalents (with fallbacks included so nothing changes on systems where `$XDG_DATA_HOME` or `$XDG_DATA_DIRS` are unset). It also silences the warnings when nonexistent directories are returned from `StandardPaths.cpp::font_directories()`, since that is to be expected with the updated code that checks for more possible directories.

2024-06-03 21:03 UTC, ADKaster requested changes

2024-06-03 21:03 UTC, ADKaster commented on Userland/Libraries/LibCore/StandardPaths.cpp
> +#    endif
This should be more like:

```c++
auto data_directories = Core::Envrionment::get("XDG_DATA_DIRS").value_or("/usr/local/share:/usr/share"sv);
data_directories.for_each_split_view(':', [&paths](auto data_directory) {
   paths.append(TRY(String::formatted("{}/fonts"sv, data_directory)));
   paths.append(TRY(String::formatted("{}/X11/fonts"sv, data_directory)));
});
```

2024-06-03 21:03 UTC, ADKaster commented on Userland/Libraries/LibCore/StandardPaths.cpp
> +    Vector paths = Vector { {
auto plz

2024-06-03 21:03 UTC, ADKaster commented on Userland/Libraries/LibGfx/Font/FontDatabase.cpp
> +        if (root_or_error.error().code() == ENOENT) {
`if (root_or_error.error().is_errno() && root_or_error().code() == ENOENT)`

2024-06-03 22:00 UTC, ADKaster commented
Whoops, looks like the code I gave you, or the edits you made (either or) are now causing a use after free https://github.com/LadybirdWebBrowser/ladybird/actions/runs/9357541272/job/25757496121?pr=31#step:14:47

Do feel free to resolve resolved comments yourself btw, the only people who can do that on github are the author and people with write access.

2024-06-03 22:16 UTC, easrng commented
the tests pass locally so idk how to fix this with no debug feedback...

2024-06-05 07:36 UTC, fgaz commented
fyi this was temporarily fixed downstream by hardcoding the nixos font path in https://github.com/NixOS/nixpkgs/pull/315048

2024-06-06 16:16 UTC, ADKaster commented
The bug was that you had 

```
Core::Environment::get("XDG_DATA_DIRS"_string).value_or("/usr/local/share:/usr/share"_string);
```

However, Core::Environment::get() returns `Optional<StringView>`. So when XDG_DATA_DIRS was not defined, we use-after-free'd the temporary string in the value_or branch.

The fix is straightforward: Don't use temporary strings, use stringview literals

```
Core::Environment::get("XDG_DATA_DIRS"sv).value_or("/usr/local/share:/usr/share"sv);
```

I'll push this tiny fix to your branch and merge it soon

2024-06-06 16:42 UTC, merged